#!/usr/bin/env python3
"""Lab token tool: create a signing key, publish its JWKS, mint agent tokens.

  python3 scripts/tokens.py init                 # new key pair + keys/jwks.json
  python3 scripts/tokens.py mint orchestrator    # print a 1-hour token for that agent
  python3 scripts/tokens.py mint worker --ttl 300
  python3 scripts/tokens.py policy > manifests/20-jwt-policy.yaml   # gateway policy trusting this key

Needs: pip install pyjwt cryptography
This stands in for an identity provider (Keycloak, Entra ID). Lab use only.
"""
import argparse, base64, json, pathlib, time, uuid

import jwt
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa

KEYS = pathlib.Path(__file__).resolve().parent.parent / "keys"
ISSUER = "https://idp.agentic-lab.local"
AUDIENCE = "agentgateway"


def b64(n: int) -> str:
    raw = n.to_bytes((n.bit_length() + 7) // 8, "big")
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode()


def init() -> None:
    KEYS.mkdir(exist_ok=True)
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    kid = "lab-" + uuid.uuid4().hex[:8]
    pem = key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption(),
    )
    (KEYS / "private.pem").write_bytes(pem)
    (KEYS / "kid").write_text(kid)
    pub = key.public_key().public_numbers()
    jwks = {"keys": [{"kty": "RSA", "use": "sig", "alg": "RS256", "kid": kid,
                      "n": b64(pub.n), "e": b64(pub.e)}]}
    (KEYS / "jwks.json").write_text(json.dumps(jwks))
    print(f"wrote {KEYS}/private.pem and {KEYS}/jwks.json (kid {kid})")


def mint(sub: str, ttl: int) -> None:
    now = int(time.time())
    claims = {"iss": ISSUER, "aud": AUDIENCE, "sub": sub,
              "iat": now, "nbf": now, "exp": now + ttl, "jti": uuid.uuid4().hex}
    token = jwt.encode(claims, (KEYS / "private.pem").read_bytes(), algorithm="RS256",
                       headers={"kid": (KEYS / "kid").read_text()})
    print(token)


POLICY = """# GENERATED by scripts/tokens.py policy - do not edit by hand.
# Every request through the gateway must carry a token signed by the lab key.
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: require-agent-identity
  namespace: agentgateway-system
  labels:
    csf-function: protect
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: agentgateway-proxy
  traffic:
    jwtAuthentication:
      mode: Strict
      providers:
      - issuer: {issuer}
        audiences:
        - {audience}
        jwks:
          inline: '{jwks}'
"""


def policy() -> None:
    jwks = (KEYS / "jwks.json").read_text().strip()
    print(POLICY.format(issuer=ISSUER, audience=AUDIENCE, jwks=jwks), end="")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    sp = p.add_subparsers(dest="cmd", required=True)
    sp.add_parser("init")
    sp.add_parser("policy")
    m = sp.add_parser("mint")
    m.add_argument("sub")
    m.add_argument("--ttl", type=int, default=3600)
    a = p.parse_args()
    if a.cmd == "init":
        init()
    elif a.cmd == "policy":
        policy()
    else:
        mint(a.sub, a.ttl)
